# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-kasa

# >> macros
# << macros

Summary:    Kasa
Version:    0.2.1
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        https://github.com/black-sheep-dev/harbour-kasa/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-kasa.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
Kasa is a native Sailfish OS application to control TP-Link Kasa smarthome devices.

%if "%{?vendor}" == "chum"
PackageName: Kasa
Type: desktop-application
Categories:
  - Tools
Custom:
  Repo: https://github.com/black-sheep-dev/harbour-kasa/
Icon: https://github.com/black-sheep-dev/harbour-kasa/raw/master/icons/harbour-kasa.svg
Screenshots:
  - https://github.com/black-sheep-dev/harbour-kasa/raw/master/metadata/screenshot1.png
  - https://github.com/black-sheep-dev/harbour-kasa/raw/master/metadata/screenshot2.png
  - https://github.com/black-sheep-dev/harbour-kasa/raw/master/metadata/screenshot3.png
Url:
  Donation: https://www.paypal.com/paypalme/nubecula/1
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
